### ISSUE TITLE
Draft a SNWG OSS practical guidance for solution teams to refer to. 

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#67]
### Milestone

M1 Open Source Science (OSS)

### Quarter

Q1 (1 Oct to 31 Dec)

### Description

Draft the following OSS guidelines for SNWG projects in an attractive, easy-to-read, and share format

### Examples

[Open Source Guide](https://opensource.guide/)
[Your pre-launch checklist for being an Open Source Project](https://opensource.guide/starting-a-project/#your-pre-launch-checklist)

### Deliverable

- [x] Meetings/Workshops: expectations for how to conduct open meetings/workshops with outcomes published in the open (agency-agnostic)
- [x] Software: published in the open for community collaboration
- [x] Articles/Algorithm Theoretical Basis Documents (ATBD): 
- [x] Project information: Earthdata hosting as standard

### Implementation Blockers or Dependencies

None currently identified

**Comment by CherrelleTucker** [comment]
CASEI Example: https://docs.google.com/presentation/d/1mBv9aRnXgXfHMzQMfdqZMBrgfq2Q0D_W6vYwPE8Cf-o/edit?userstoinvite=heidimok%40developmentseed.org&sharingaction=manageaccess&role=writer#slide=id.g28080677a62_1_0

**Comment by CherrelleTucker** [comment]
[Open Science Considerations.pdf](https://docs.google.com/presentation/d/1OOHgdqS82E81P7jXNxJzGsByJ-Wfh_RZPFakczECp4A/edit#slide=id.p)

Notes from OS101 course that may be applicable to developing a practical guide for solution teams

**Comment by CherrelleTucker** [comment]
[2023-12-14 11:10 AM] Tucker, Cherrelle J. (MSFC-ST11)[Consolidated Program Support Services]
Sheyenne just sent over MAAP's OSS documentation. It is fantastic! They also have a PR out to add the link to the new Open Science curriculum per Alex and Brian's idea. 
 
(https://docs.maap-project.org/en/develop/system_reference_guide/oss_documentation.html)
[Open Source Science — maap-docs  documentation]


[Open Source Science Guidance | Science Mission Directorate](https://smd-cms.nasa.gov/wp-content/uploads/2023/12/smd-open-source-science-guidance-v2.1-20231211-2.pdf)
 
Sheyenne also shared this with me, which may be just exactly what we need. It's not exactly an easy doc to find hosted unless you know that you are looking for it.
