### ISSUE TITLE
Draft documentation and templates needed for the Formulation and Implementation of 2022 solutions.

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#69]
### Milestone

M3 Cycle 4

### Quarter

Q1 (1 Oct to 31 Dec)

### Description

Draft documentation and templates needed for the Formulation and Implementation of 2022 solutions.

### Examples and Resources

[The purpose of this system level procedure (SLP) is to establish a consistent and documented method for acquiring products and/or services for the NASA IV&V Program.](https://www.nasa.gov/wp-content/uploads/2015/09/ivv_06_procurement_ver_x_09-27-2019.pdf)

[SNWG Solutions Milestones - Contracting Types and Processes Sheet](https://docs.google.com/spreadsheets/d/1X9vZoSQqxXayuoBpgAJNW9t5oLYVKWdEk6jOOHCznFY/edit#gid=110537420)

[Goddard Office of Procurement Portal and Documentation](https://code200-external.gsfc.nasa.gov/210/node/136)

### Deliverable

Contract type-specific Schedule/Process, (process steps that Larry, Eric, and Sean have been gathering this past couple of quarters)
  - [ ] TTA (NASA Center)
  - [ ] IAA (Other Government Agency)
  - [ ] Task Plan (JPL)
  - [ ] External Contract (ex. SAO)
 
- [x] #70

### Implementation Blockers or Dependencies

None currently identified
