### ISSUE TITLE
Complete PBL Authority To Proceed equivalent 

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#72]
### Milestone

M4 Cycle 3

### Quarter

Q1 (1 Oct to 31 Dec)

### Description

[SNWG MO-PBL ATP DG Decision Memorandum_v0.0](https://docs.google.com/document/d/1o1zqSEFc64AKeembvZDfva3OVBYPbOfNIIvX5wlYIQk/edit?usp=drive_link)
[SNWG MO-PBL Project Plan_v0.1](https://docs.google.com/document/d/19y9tWLVM692cPs8pbYdNS7rt_zcXhSg9KcFNr72eA60/edit?usp=drive_link)

### Deliverable

- [ ] Deviation from Procedure Memo
- [x] MO to review Preliminary Project Plan and provide feedback within 10 working days of receipt from JPL
- [ ] Project Plan Review Memo in the stead of ATP DG memo. 

### Implementation Blockers or Dependencies

- Timely JPL delivery of preliminary project plan

**Comment by CherrelleTucker** [comment]
“Next steps” meeting 11/7 with JPL [2023-11-07 SNWG MO/PBL Next Steps ](https://docs.google.com/document/d/1G_5bvc11RVb54XECzC5dSh_cSgsFpBjS9Sen62BRft8/edit)

**Comment by CherrelleTucker** [comment]
Meeting with Jennifer Cruz + JPL PBL team Jan 09, 2024 to discuss the project plan template
Meeting invite forwarded to Pontus, Jeanne`, and Jenny. 
[2024-01-08 SNWG MO Internal Planning Meeting](https://docs.google.com/document/d/1jXwosXFMD0lq-0ktAQTtVDR6pdu5blHsky222T8sy-I/edit)

Objective closed with A.C. moved to next PI. Timely JPL delivery of preliminary project plan prevented the completion of

- Deviation from Procedure Memo
- Project Plan Review Memo in the stead of ATP DG memo.
