### ISSUE TITLE
Execute Phase 2 of the SNWG-SPoRT 3 Solution Engagement Plan

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#79]
### Milestone

M6 Stakeholder Engagement Program (SEP)

### Quarter

Q1 (1 Oct to 31 Dec)

### Description

Execute Phase 2 of the [SNWG-SPoRT 3 Solution Engagement Plan](https://docs.google.com/document/d/1fjZK1uMK4U3QbnirmYtqR4XMz5FsFDg18vFhkeF_giA/edit)

Phase 2: Stakeholder Meetings (0.50 FTE)
TEMPO: 	        Timetable: FY23 2/3/4Q & beyond FTE: 0.16
Pandora: 	        Timetable: FY23 2/3/4Q & beyond FTE: 0.16
PBL: 		Timetable: FY23 2/3/4Q & beyond FTE: 0.16

Objectives
O.1. Engage and develop stakeholder/early adopter group for testing, assessments, & feedback.
O.2. Identify additional gaps/needs/requirements not previously identified and communicate to
SNWG-Management Office and Implementation Leads.

Tasks
T.1. Coordinate regular stakeholder engagement meetings (bi-monthly)
T.2. Coordinate regular solution/implementation lead meetings (monthly-to-bi-monthly)
T.3. Attend monthly SNWG implementation lead meetings
T.4. Formulate question list with input from solution/implementation leads
T.5. Host application-based seminars/webinars to expand stakeholder/end-user base
T.6. Market/recruit additional stakeholders & end-users for needs/requirements and for Assessment

### Deliverable

- [x] D.1. Updates and feedback from 4-6 meetings with implementation leads
- [x] D.2. Monthly SNWG implementation lead meetings
- [x] D.3. Engagement/feedback from 3-6 stakeholder meetings
- [x] D.4. Two webinars/outreach sessions for recruitment of additional stakeholders/end-users

### Implementation Blockers or Dependencies

none currently identified

**Comment by CherrelleTucker** [comment]
@ALeRoy55 , can you add dates and details for the meetings fulfilling the deliverables here?

**Comment by CherrelleTucker** [comment]
-	D.1. Updates and feedback from 4-6 meetings with implementation leads
-Pandora / AQ requested clarity on who (or what agency) can select sites. USDS sites have not been selected yet.
-TEMPO team is working with SPoRT to socialize TEMPO first light imagery.
-	D.2. Monthly SNWG implementation lead meetings
-Pandora /AQ is on a monthly cadence for implementation team check-ins. TEMPO is ad hoc due to launch business, but has logged two check-ins since August. PBL check-ins occur about every other month.
Pandora check-ins: Oct. 23, Nov. 27
Pandora stakeholder meetings: Nov. 9
TEMPO check-ins: Oct. 25
TEMPO stakeholder meetings: Nov. 30
PBL check-in: Nov. 13
-	D.3. Engagement/feedback from 3-6 stakeholder meetings
-Pandora / AQ stakeholder meetings are currently used to facilitate choosing the site location for Pandora sensors. 
-TEMPO stakeholder meetings have brought to light some confusion from stakeholders about the scope of NRT products. A follow-up meeting with EPA and TEMPO implementation team lead will be scheduled to help provide needed clarity to stakeholders.
-	D.4. Two webinars/outreach sessions for recruitment of additional stakeholders/end-users
-TEMPO, PBL, and Pandora/AQ will soon be featured Stakeholder Summit topics designed to reach new stakeholders and inform current users. Dates TBD, but targeting Feb-June 2024. Summits are virtual, and they feature breakout rooms for discussion topics and provide an avenue for product developers to speak to many different stakeholders at once.

**Comment by CherrelleTucker** [comment]
Anita is adding me to the SPoRT calendar tracking Teams so that I can add specific dates to update in the coming PI.
