### ISSUE TITLE
Progress SNWG OSS policies and guidelines for solution teams to refer to. 

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#82]
### Milestone

M1 Open Source Science (OSS)

### Quarter

Q2 (1 Jan to 31 Mar)

### Description

Summary: 
Finalize SNWG OSS policies and guidelines for solution teams to refer to. 
Owner: Pontus Olofsson
Acceptance Criteria:
Draft the following OSS guidelines for SNWG projects in an attractive, easy-to-read, and share format: 
Meetings/Workshops guidelines: expectations for how to conduct open meetings/workshops with outcomes published in the open (agency-agnostic)
Software guidelines: published in the open for community collaboration (Cherrelle to train in the process as IMPACT PoC)
Articles/Algorithm Theoretical Basis Documents (ATBD guidelines): 
Project information: document Earthdata hosting as standard in the [Open Science Practical Guidance](https://docs.google.com/presentation/d/1OOHgdqS82E81P7jXNxJzGsByJ-Wfh_RZPFakczECp4A/edit#slide=id.p) 

Future PI: 
Just FYI: Pontus is our TOPS Champion.

### Deliverable

- [ ] Meetings/Workshops guidelines: expectations for how to conduct open meetings/workshops with outcomes published in the open (agency-agnostic)
- [ ] Software guidelines: published in the open for community collaboration (Cherrelle to train in the process as IMPACT PoC)
- [ ] Articles/Algorithm Theoretical Basis Documents (ATBD guidelines)
- [ ] Project information: document Earthdata hosting as standard in the [Open Science Practical Guidance](https://docs.google.com/presentation/d/1OOHgdqS82E81P7jXNxJzGsByJ-Wfh_RZPFakczECp4A/edit#slide=id.p)

### Implementation Blockers or Dependencies

Dependencies:
None currently identified
Risks
None currently identified

### Related Issues

#67

**Comment by CherrelleTucker** [comment]
Further developing in response to feedback from Natasha. Carry over to next PI
