### ISSUE TITLE
Draft process documentation and templates needed for the Formulation and Implementation of 2022 solutions.

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#84]
### Milestone

M3 Cycle 4

### Quarter

Q2 (1 Jan to 31 Mar)

### Description

Obj 3.A Summary: 
Draft process documentation and templates needed for the Formulation and Implementation of 2022 solutions.
Owner: Eric Taylor, Jenny Wood, Jeanne’ le Roux, Sean Gregory, Cherrelle Tucker, Pontuss Olofsson

Future PI: 
ORR templates - to be created as needed

### Deliverable

- [x] Contract type-specific Process “Implementation Cheat Sheet”
-- TTA (NASA Center)
-- IAA (Other Government Agency)
-- Task Plan (JPL)
-- External Contract (ex. SAO)
- [ ] Review and update “Welcome to [SNWG MO Intro Presentation](https://docs.google.com/presentation/u/0/d/1ddKMq9M062ekIBbbS0i_aH0W0TE-d2f5gOPLSBBBIBU/edit)”. Audience: Project leads for new solutions; High-level overview (not a deep dive). Pontus can modify for an audience familiar with ROSES.
- [x] Assess whether template changes are needed & write Request for Proposal/Science Statement of Work documents for selected 2022 solutions

### Implementation Blockers or Dependencies

Dependencies:
None currently identified
Risks
None currently identified

**Comment by CherrelleTucker** [comment]
2024-02-21 Financial/contracts meeting

JPL wants generic JPL task plan (programmatic-level), JPL PLRA Appendix (L1 req common to each individual solution they work on), JPL PLRA Annex (per solution and any unique solution requirements). “One pager” will be developing VLM-specific PLRA-Annex

**Comment by CherrelleTucker** [comment]
Larry created a draft task plan template and sent it to David B. 
This will be a major topic of discussion during David B.’s visit to MSFC the week of March 4 
There’s not much mention of SEP in the drafted plan. Action: Pontus draft separate SEP plan (2-3 pages) for VLM to supplement the VLM task plan. 
Discussion is needed on VLM SEP strategy; stakeholders will be the same as the dist product. Is SEP funding embedded in the current proposal or is it an external fund? Verify currently proposed funding flow.

[2024-02-26 SNWG MO Internal Planning Meeting](https://docs.google.com/document/d/1xl5oRVh-k8xlpNRxAzc97cNOSkSyWpEFNw9O9CFkGTA/edit)

**Comment by CherrelleTucker** [comment]
Break out "Review and update “Welcome to [SNWG MO Intro Presentation](https://docs.google.com/presentation/u/0/d/1ddKMq9M062ekIBbbS0i_aH0W0TE-d2f5gOPLSBBBIBU/edit)”. Audience: Project leads for new solutions; High-level overview (not a deep dive). Pontus can modify for an audience familiar with ROSES." to SEP Objective. Other criteria are complete.

**Comment by CherrelleTucker** [comment]
Eric has created an excel sheet with list of templates to review, create, align with naming conventions for future PI.
