### ISSUE TITLE
Complete PBL Authority To Proceed equivalent 

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#86]
### Milestone

M4 Cycle 3

### Quarter

Q2 (1 Jan to 31 Mar)

### Description

Obj 4.B Summary: 
Baseline Pandora Sensors Project Plan and prepare for F2I Decision Gate
Owner: Sean Gregory 

### Deliverable

- [ ] Prepare Deviation from Procedure Memo
- [x] MO to review Preliminary Project Plan (or alternative agreed to documentation) and provide feedback within 10 working days of receipt from JPL
- [ ] Prepare Project Plan Review Memo in the stead of ATP DG memo 

### Implementation Blockers or Dependencies

Dependencies:
Timely JPL delivery of preliminary project plan/alternative agreed to documentation
Risks
None currently identified

### Related Issues

#73 
#42 
#14 
#6 
#2

**Comment by CherrelleTucker** [comment]
[2024-01-22 SNWG MO Monthly Project Update Meeting](https://docs.google.com/document/d/1QZh-uv1LAusW3gk4hj2DyJW_WCpAg61-SDDMsJURnGk/edit):
Working towards draft preliminary project plan / equivalent documentation, including data product requirements, to inform upcoming Authority To Proceed Checkpoint (not yet scheduled).

**Comment by CherrelleTucker** [comment]
[2024-02-26 SNWG MO Monthly Project Update Meeting](https://docs.google.com/document/d/1C6zM4g1PVP0S-dYmqRQh1Qh476lRzjfAW2urHH8dUCk/edit): Work on project plan ongoing, project and data product requirements drafted. Authority To Proceed Checkpoint is an upcoming milestone.
Action: Cherrelle verify PBL ATP dates. (email sent to Heidar 2024-03-19)

**Comment by CherrelleTucker** [comment]
From: "Tucker, Cherrelle J. (MSFC-ST11)[Consolidated Program Support Services]" <[cherrelle.j.tucker@nasa.gov](mailto:cherrelle.j.tucker@nasa.gov)>
Date: Tuesday, March 19, 2024 at 11:13 AM
To: "Thrastarson, Heidar T (US 329E)" <[heidar.t.thrastarson@jpl.nasa.gov](mailto:heidar.t.thrastarson@jpl.nasa.gov)>
Subject: PBL ATP Decision Gate check in

Good afternoon, Heidar!
 
I’m following up on an action from the February SNWG Monthly to check in on project plan progress and preparation for the next PBL milestone: the Authority to Proceed Decision Gate. Will it be feasible to schedule that within the next month or does the team need more time and/or guidance to get to that point?  
 
Thanks!
Cherrelle Tucker 🙭SNWG MO Project Coordinator

----------------------------------

From: Thrastarson, Heidar T (US 329E) <[heidar.t.thrastarson@jpl.nasa.gov](mailto:heidar.t.thrastarson@jpl.nasa.gov)> 
Sent: Wednesday, March 20, 2024 6:22 PM
To: Tucker, Cherrelle J. (MSFC-ST11)[Consolidated Program Support Services] <[cherrelle.j.tucker@nasa.gov](mailto:cherrelle.j.tucker@nasa.gov)>
Cc: Teixeira, Joao P (JPL-3290)[JPL Employee (FN) LPR] <[joao.teixeira@jpl.nasa.gov](mailto:joao.teixeira@jpl.nasa.gov)>; Ao, Chi O (JPL-335G)[JPL Employee] <[chi.o.ao@jpl.nasa.gov](mailto:chi.o.ao@jpl.nasa.gov)>
Subject: Re: PBL ATP Decision Gate check in

Hello, Cherrelle. 

Thanks for the follow-up. 

We did receive some guidance on expected input for the ATP Checkpoint, in the table copied below, sent by Jeanne. 

Should we share the relevant documentation in our case (Preliminary Project Plan with draft Program Level Requirements and draft Task Plan) with some specific advance time before the time of the ATP Checkpoint?

Thanks, 
 - Heidar.
------------------------------------------------------
From: Tucker, Cherrelle J. (MSFC-ST11)[Consolidated Program Support Services] <cherrelle.j.tucker@nasa.gov> 
Sent: Thursday, March 21, 2024 9:14 AM
To: Thrastarson, Heidar T (JPL-329E)[JPL Employee] <heidar.t.thrastarson@jpl.nasa.gov>; Jeanne le Roux <jeanne.leroux@nsstc.uah.edu>; Jenny Wood <jmw0057@uah.edu>
Cc: Teixeira, Joao P (JPL-3290)[JPL Employee (FN) LPR] <joao.teixeira@jpl.nasa.gov>; Ao, Chi O (JPL-335G)[JPL Employee] <chi.o.ao@jpl.nasa.gov>
Subject: Re: PBL ATP Decision Gate check in

I think it would be quite helpful for your team to share your prepared materials with Jeanne'. We can then move forward from there 🙂

Cherrelle Tucker 🙭SNWG MO Project Coordinator
NASA MSFC IMPACT
Barrios Technologies
Cramer Research Hall/NSSTC #3058

**Comment by CherrelleTucker** [comment]
Move to next PI
