### ISSUE TITLE
Baseline Pandora Sensors Project Plan and prepare for F2I Decision Gate

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#87]
### Milestone

M4 Cycle 3

### Quarter

Q2 (1 Jan to 31 Mar)

### Description

Obj 4.B Summary: 
Baseline Pandora Sensors Project Plan and prepare for F2I Decision Gate
Owner: Sean Gregory 
Acceptance Criteria: 
Finalize and sign the Pandora Sensors Project Plan
Schedule Formulation to Implementation Decision Gate for PM2.5 and GMAO 
GMAO Forecasts: March 2024 (hold future PI) 
PM2.5 Forecasts: March 2024 (hold future PI)

### Deliverable

- [ ] Finalize and sign the Pandora Sensors Project Plan
- [x] Schedule Formulation to Implementation Decision Gate for PM2.5 and GMAO 
- [x] GMAO Forecasts: March 2024 (hold future PI) 
- [x] PM2.5 Forecasts: March 2024 (hold future PI)

### Implementation Blockers or Dependencies

Signature from the Pandora Sensors project lead
The Project Plan was modified slightly to account for site selection difficulties and these changes need to be approved by the Pandora Sensors project lead 
Risks
None currently identified

**Comment by CherrelleTucker** [comment]
GMAO F2I DG: 2024-05-01 •	[Meeting Notes/Agenda](https://docs.google.com/document/d/1kImvTURa5fUxBMNQxdn8L50EFPg-K59uT-8xGrzlQo8/edit)
PM2.5 F2I DG: 2024-04-25 •	[Meeting Notes/Agenda](https://docs.google.com/document/d/1kImvTURa5fUxBMNQxdn8L50EFPg-K59uT-8xGrzlQo8/edit)

**Comment by CherrelleTucker** [comment]
As of 2024-03-19: [Pandora Sensors Project Plan] "Still in progress. I need to follow up and send it to him again." - Sean Gregory

**Comment by CherrelleTucker** [comment]
2024-03-21 Standup: Reviewing potential SEP additions. May delay signing.
