### ISSUE TITLE
Progress HLS-VI 

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#89]
### Milestone

M4 Cycle 3

### Quarter

Q2 (1 Jan to 31 Mar)

### Description

Obj 4.D Summary: 
Progress HLS-VI 
Owner: Sean Gregory 

### Deliverable

- [ ] Finalize and sign the HLS-VI project plan
- [ ] Finalize and sign the HLS-VI F2I DG Memo
- [x] Schedule Operational Readiness Review (ORR) 
- [x] Explore potential handoff options

### Implementation Blockers or Dependencies

Dependencies:
Open questions about appropriate handoff plan will require input from HQ
Risks
None currently identified
Future PI: 
Hold Operational Readiness Review (ORR)

**Comment by CherrelleTucker** [comment]
HLS-VI ORR tentatively scheduled April 1. - confirmed with Madhu

**Comment by CherrelleTucker** [comment]
I can have that [section of the HLS-VI project plan] ready by the end of the week - Madhu; 2024-03-19

**Comment by CherrelleTucker** [comment]
2024-03-20 Financial: trying to get in touch with Karen Michael, no response yet.
