### ISSUE TITLE
Implement and document process for collecting success metrics identified in PI 24.1

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#92]
### Milestone

M5 Cycle 1 & 2

### Quarter

Q2 (1 Jan to 31 Mar)

### Description

Objective 5.C Summary: 
Implement and document process for collecting success metrics identified in PI 24.1
Owner: Pontus Olofsson, Katrina Virts, Sean Gregory

### Deliverable

- [x] Gather and review feedback across thematic areas and agencies
- [x] Review DAAC metrics for use. 
- [x] Receive and apply HQ guidance on success stories and user metrics to provide proof of solution value.

### Implementation Blockers or Dependencies

**Dependencies**:
None currently identified
**Risks**
None currently identified
**Future PI:**

**Comment by CherrelleTucker** [comment]
[snwg_dist_dec23](https://docs.google.com/spreadsheets/d/1hUPZNheWVEe3NEm6way8KKmA6jlQFiQ-/edit?usp=drive_link&ouid=106604293755679367477&rtpof=true&sd=true)

[solution usage metrics folder](https://drive.google.com/drive/folders/1hyzZ_MSB-pnvB9brO8g9IrVWhBsoDg1G)

**Comment by CherrelleTucker** [comment]
2024-04-02: SEP Guidance document/Template for solution Projects
