### ISSUE TITLE
Execute Phase 2 of the SNWG-SPoRT 3 Solution Engagement Plan

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-implementation#93]
### Milestone

M6 Stakeholder Engagement Program (SEP)

### Quarter

Q2 (1 Jan to 31 Mar)

### Description

Objective 6.A Summary: 
Execute Phase 2 of the [SNWG-SPoRT 3 Solution Engagement Plan](https://sharepoint.msfc.nasa.gov/sites/st/ST10/ST11/IMPACT/Financials/SNWG-SPoRT_3-Solution_Engagement_Plan.pdf)

Owner: Pontus Olofsson, Anita LeRoy, Cherrelle Tucker

### Deliverable

- [x] Ph2D.3. Engagement/feedback from 3-6 stakeholder meetings
- [x] Ph2D.4. One  webinar/outreach sessions for recruitment of additional stakeholders/end-users
- [x] Ph3D.3. 4-6 meetings with implementation leads

### Implementation Blockers or Dependencies

**Dependencies**:
Participation of solution project teams
**Risks**
None currently identified
**Future PI: **

**Comment by CherrelleTucker** [comment]
Completed as of 2024-03-19:

- 2024-01-31: Meet with Tom Hanisco at AMS - Ask about walls preventing sensor installments, how we can help move things forward
- 2024-02-09: Draft gap analysis reports - Anita to start consolidating "need, requirements, and gaps" reports.
- 2024-02-15: EPA user story for SNWG-MO - Reach out to EPA contacts and ask for specific information on how TEMPO will help them or aid in specific decisions.
Make a quick slide describing the story =)
- 2024-02-23: (TEMPO) Discuss Training Needs with Aaron 
- 2024-02-23: Reach out to USDA re: Pandora sensors 
- 2024-03-24: Aggregate Stakeholder Responses w/ Previous Surveys into Master List: recurring
